### ISSUE TITLE
Multilang selector

### ISSUE THREAD

**Issue by alecrt** [jbreuer/1-1-multilingual-example#1]
Hi @jbreuer,

nice work. I'm quite new to Model Builder but i got everything working quite good now.

Just a question: could you give me some hint on how to obtain a multilang selector in razor view? I did't found any method in the UmbracoHelper to obtain a url based on Culture parameter.

Another idea could be building a dictionary of the IPublished content urls, based on cultureAlias keys

Thanks in advance!

**Comment by alecrt** [comment]
Ok, found something i think is quite fast. Plz give me your feedback!

``` c#
<ul>
    <li>
        <a href="@Model.Content.Url">@Model.Content.GetCulture(new Uri(Model.Content.Url)).EnglishName</a>
    </li>
    @foreach (var url in Umbraco.UrlProvider.GetOtherUrls(Model.Content.Id).OrderBy(t => t))
    {
        <li>
            <a href="@url">@Model.Content.GetCulture(new Uri(url)).EnglishName</a>
        </li>
    }
</ul>
```

**Comment by jbreuer** [comment]
Hi Alecrt,

I haven't created something like this before, but the example that you've created looks good :-).

Jeroen

**Comment by alecrt** [comment]
Cool, i close.
Thanks m8
