### ISSUE TITLE
1-1-multilingual-example for Umbraco 7.3.X

### ISSUE THREAD

**Issue by bhavikm05** [jbreuer/1-1-multilingual-example#3]
Hi Jeroen 

This is a very good example. I would like to propose this 1-1 multilingual solution to my project, but the issue is that we are using Umbraco 7.3.8 version and your solution is in the umbraco 7.4.X version which is not working for lower version. (due to Model Builder). Do you have solution in 7.3.8 version?

**Comment by jbreuer** [comment]
Hello,

The project actually started as a 7.3 project and I later upgraded to 7.4. So if you check the commits you can also find the 7.3 version: https://github.com/jbreuer/1-1-multilingual-example/commits/master

Latest 7.3 version: https://github.com/jbreuer/1-1-multilingual-example/tree/05198100a8c7b013d9f9674fa600f068ca667c4d

7.4 project with older version of the Models Models (zbu): https://github.com/jbreuer/1-1-multilingual-example/tree/b0b2daadb4aadb01ba49a4c078bb86e9f0b855e4

Between the 7.3 and 7.4 version I did make some improvements so you might have to compare them.

**Comment by bhavikm05** [comment]
Thanks for update. I will close this issue.  By the why your example is great. I really appreciate your hard work for this.
