### ISSUE TITLE
How to build in visual studio 2012 for web

### ISSUE THREAD

**Issue by mrpeo** [jbreuer/1-1-multilingual-example#4]
I can't build this source using visual studio 2012 for web.

The errors shows in screenshot.

Can anyone help me?

Thank you very much!

![screend](https://cloud.githubusercontent.com/assets/4709861/17209889/a62d88dc-54e9-11e6-8a16-130cea8acaf3.jpg)

**Comment by jbreuer** [comment]
If you build the project those references should be downloaded with NuGet.

**Comment by mrpeo** [comment]
But in Umbraco.Extensions shows these abow errors. 

:(

**Comment by mrpeo** [comment]
Already run success in visual studio 2013.

Thank you for supports
