### ISSUE TITLE
database for SQL Server (* .sql)

### ISSUE THREAD

**Issue by gregoriii** [jbreuer/1-1-multilingual-example#8]
Will it be possible sharing database for SQL Server (\* .sql). What has been added to the standard Umbraco database (tables, procedures, index)?

**Comment by jbreuer** [comment]
It's possible to migrate SQL CE to SQL Server. More info here: http://erikej.blogspot.nl/2012/02/migrating-databases-between-sql-server.html - https://github.com/ErikEJ/SqlCeToolbox
